name:                rl-srl-web
version:             0.1.0.0
github:              LarsVadgaard/rl-srl-web
license:             BSD3
author:              "Lars Vadgaard"
maintainer:          "lars@vadg.io"
copyright:           "2022 Lars Vadgaard"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rl-srl-web#readme>

dependencies:
- base >= 4.14 && < 5
- scotty >= 0.12
- parsec >= 3.0
- monad-loops >= 0.4.3
- unordered-containers >= 0.2.9
- containers >= 0.5.10.2
- mtl >= 2.2
- filepath >= 1.4
- regex-compat >= 0.95.1
- directory >= 1.3.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rl-srl-web:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl-srl-web

tests:
  rl-srl-web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rl-srl-web
